services:
  # API Gateway - Único servicio activo
  ingesta-api:
    build: ./api-gateway
    image: pharmavida_ingesta:latest
    container_name: pharmavida_ingesta
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    networks:
      - pharmavida_network

networks:
  pharmavida_network:
    driver: bridge